#define GOLEM_HEALTH_LOW 50
#define GOLEM_HEALTH_MED 100
#define GOLEM_HEALTH_HIGH 150
#define GOLEM_HEALTH_ULTRA 200

#define GOLEM_DMG_LOW 15
#define GOLEM_DMG_MED 25
#define GOLEM_DMG_HIGH 40
#define GOLEM_DMG_ULTRA 55

#define GOLEM_SPEED_SLUG 9
#define GOLEM_SPEED_LOW 7
#define GOLEM_SPEED_MED 5
#define GOLEM_SPEED_HIGH 3


#define GOLEM_ARMOR_LOW 20
#define GOLEM_ARMOR_MED 35
#define GOLEM_ARMOR_HIGH 50
#define GOLEM_ARMOR_ULTRA 65
